### ISSUE TITLE
[Shell] Sanitize User Input

### ISSUE THREAD

**Issue by graphicore** [FontBureau/TypeRoof#5]
David Berlow created the following condition by inputting the empty string into the "Time Duration " control and the app wasn't able to recover from it:

```
update @ generic.mjs:195
1000animation-animanion.mjs:319 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'at')
    at getPropertyValue (animation-animanion.mjs:319:59)
    at getPropertyValues (animation-animanion.mjs:351:23)
    at LocalScopeAnimanion._getPropertyValuesMapForAbsoluteT (animation-animanion.mjs:564:16)
    at LocalScopeAnimanion.getPropertyValuesMapForAbsoluteT (animation-animanion.mjs:572:29)
    at LocalScopeAnimanion.getPropertyValuesMapForLocal
```

I was coming around to this, however, it's really bad for demoing and needs to be resolved.

* Input fields should not accept invalid/un-parsable input.
* The app should be able to recover, otherwise work will be lost!

**Comment by graphicore** [comment]
All simple DataModels are now validated and can be sanitized as well.
